"use client";

import { motion } from "framer-motion";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  User,
  ArrowRight,
  CreditCard,
  Image,
  Phone,
  Upload,
  X,
  Lock,
  Sparkles,
} from "lucide-react";
import toast from "react-hot-toast";
import { Button } from "@/components/button";
import { Input } from "@/components/input";
import { SlideIn } from "@/components/animations";
import { AuthHeader } from "@/components/common/AuthHeader";
import { useAuth } from "@/contexts/AuthContext";
import Link from "next/link";
import {
  registrationSchema,
  type RegistrationFormData,
} from "@/schema/auth.schema";

export default function RegisterPage() {
  const router = useRouter();
  const { register: registerUser, isLoading: authLoading } = useAuth();
  const [usernameAutoGenerated, setUsernameAutoGenerated] = useState(true);

  const {
    register,
    handleSubmit,
    formState: { errors },
    watch,
    setValue,
    trigger,
  } = useForm<RegistrationFormData>({
    resolver: zodResolver(registrationSchema) as any,
    mode: "onChange",
    defaultValues: {
      firstName: "",
      lastName: "",
      username: "",
      password: "",
      nid: "",
      nomineeName: "",
      nomineeNid: "",
      nomineePhoto: undefined,
      referenceName: "",
      phoneOrEmail: "",
      termsAccepted: false,
    },
  });

  const firstName = watch("firstName");
  const lastName = watch("lastName");
  const username = watch("username");
  const photo = watch("photo");
  const nomineePhoto = watch("nomineePhoto");

  const handleFileChange = async (
    e: React.ChangeEvent<HTMLInputElement>,
    fieldName: "photo" | "nomineePhoto"
  ) => {
    const file = e.target.files?.[0];
    if (file) {
      setValue(fieldName, file, { shouldValidate: true });
      await trigger(fieldName);
    }
  };

  const removeFile = (fieldName: "photo" | "nomineePhoto") => {
    setValue(fieldName, undefined as any, { shouldValidate: true });
  };

  const handleAutoGenerateUsername = () => {
    const first = (firstName ?? "").trim();
    const last = (lastName ?? "").trim();
    if (!first && !last) return;
    const base = (first + last)
      .toLowerCase()
      .replace(/\s/g, "")
      .replace(/[^a-z0-9]/g, "");
    const specials = "._!@";
    const suffix =
      specials[Math.floor(Math.random() * specials.length)] +
      Math.floor(10 + Math.random() * 90);
    const generated = base ? `${base}${suffix}` : `user${suffix}`;
    setValue("username", generated, { shouldValidate: true });
    setUsernameAutoGenerated(true);
  };

  const onSubmit = async (data: RegistrationFormData) => {
    const loadingToast = toast.loading("রেজিস্ট্রেশন করা হচ্ছে...");

    try {
      await registerUser(data);
      toast.dismiss(loadingToast);
      toast.success("সফলভাবে রেজিস্ট্রেশন করা হয়েছে!");

      // Redirect to login after successful registration
      setTimeout(() => {
        router.push("/login");
      }, 1000);
    } catch (error: any) {
      toast.dismiss(loadingToast);
      const errorMessage = error.message || "রেজিস্ট্রেশন ব্যর্থ হয়েছে। আবার চেষ্টা করুন।";
      toast.error(errorMessage);
      console.error("Registration error:", error);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 via-white to-accent-50 py-8">
      <div className="w-full max-w-7xl mx-auto px-4">
        {/* Logo and Header */}
        <AuthHeader
          title="রিটার্ন ভ্যাটেড"
          subtitle="আজই আপনার সঞ্চয়ের যাত্রা শুরু করুন"
        />

        {/* Registration Form */}
        <SlideIn direction="up" delay={0.3}>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="bg-white rounded-2xl shadow-xl p-8 border border-gray-100"
          >
            <form
              onSubmit={handleSubmit(onSubmit)}
              className="space-y-6"
              noValidate
            >
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Personal Information Section */}
                <div className="space-y-4 md:col-span-2">
                  <h2 className="text-lg font-semibold text-gray-800 border-b pb-2">
                    ব্যক্তিগত তথ্য
                  </h2>
                </div>

                <Input
                  label="ফর্মের প্রথম নাম"
                  type="text"
                  icon={User}
                  placeholder="ফর্মের প্রথম নাম দিন"
                  {...register("firstName")}
                  error={errors.firstName?.message}
                />

                <Input
                  label="ফর্মের শেষ নাম"
                  type="text"
                  icon={User}
                  placeholder="ফর্মের শেষ নাম দিন"
                  {...register("lastName")}
                  error={errors.lastName?.message}
                />
                <div className="flex items-start gap-2">
                  <div className="flex-1 min-w-0">
                    <Input
                      label="ইউজারনেম"
                      type="text"
                      icon={User}
                      placeholder="ইউজারনেম দিন"
                      {...register("username")}
                      error={errors.username?.message}
                    />
                    {usernameAutoGenerated && firstName && lastName && username && (
                      <p className="mt-1 text-xs text-gray-500">
                        স্বয়ংক্রিয়ভাবে তৈরি করা হয়েছে
                      </p>
                    )}
                  </div>
                  <button
                    type="button"
                    onClick={handleAutoGenerateUsername}
                    disabled={!firstName?.trim() && !lastName?.trim()}
                    title="প্রথম ও শেষ নাম থেকে ইউজারনেম তৈরি করুন"
                    className="mt-8 h-11 px-3 rounded-lg border-2 border-primary-300 bg-primary-50 text-primary-700 hover:bg-primary-100 hover:border-primary-400 disabled:opacity-50 disabled:cursor-not-allowed transition-colors inline-flex items-center gap-1.5 text-sm font-medium shrink-0"
                  >
                    <Sparkles className="h-4 w-4" />
                    Auto Generate
                  </button>
                </div>

                <Input
                  label="পাসওয়ার্ড"
                  type="password"
                  icon={Lock}
                  placeholder="পাসওয়ার্ড দিন (কমপক্ষে ৬ অক্ষর)"
                  {...register("password")}
                  error={errors.password?.message}
                />

                <Input
                  label="ফোন নম্বর"
                  type="tel"
                  icon={Phone}
                  placeholder="০১XXXXXXXXX (১০–১১ সংখ্যা)"
                  {...register("phoneOrEmail")}
                  error={errors.phoneOrEmail?.message}
                  className="md:col-span-2"
                />

                <Input
                  label="এনআইডি"
                  type="text"
                  icon={CreditCard}
                  placeholder="আপনার জাতীয় পরিচয়পত্র নম্বর দিন (১০ সংখ্যা)"
                  {...register("nid")}
                  error={errors.nid?.message}
                />

                {/* Photo Upload */}
                <div className="w-full md:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    ছবি <span className="text-red-500">*</span>
                  </label>
                  {photo ? (
                    <div className="relative">
                      <div
                        className={`flex items-center space-x-3 p-3 border-2 rounded-lg transition-colors ${errors.photo
                          ? "border-red-500 bg-red-50"
                          : "border-primary-300 bg-primary-50"
                          }`}
                      >
                        <Image className="h-8 w-8 text-primary-600" />
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium text-gray-700 truncate">
                            {photo.name}
                          </p>
                          <p className="text-xs text-gray-500">
                            {(photo.size / 1024).toFixed(2)} KB
                          </p>
                        </div>
                        <button
                          type="button"
                          onClick={() => removeFile("photo")}
                          className="p-1 hover:bg-red-100 rounded-full transition-colors"
                        >
                          <X className="h-5 w-5 text-red-600" />
                        </button>
                      </div>
                    </div>
                  ) : (
                    <label
                      className={`flex flex-col items-center justify-center w-full h-32 border-2 border-dashed rounded-lg cursor-pointer transition-colors ${errors.photo
                        ? "border-red-500 bg-red-50 hover:bg-red-100"
                        : "border-gray-300 bg-gray-50 hover:bg-gray-100"
                        }`}
                    >
                      <div className="flex flex-col items-center justify-center pt-5 pb-6">
                        <Upload
                          className={`w-8 h-8 mb-2 ${errors.photo ? "text-red-400" : "text-gray-400"
                            }`}
                        />
                        <p className="mb-2 text-sm text-gray-500">
                          <span className="font-semibold">ক্লিক করুন</span> অথবা ফাইল টেনে আনুন
                        </p>
                        <p className="text-xs text-gray-500">PNG, JPG, JPEG (সর্বোচ্চ ৫ এমবি)</p>
                      </div>
                      <input
                        type="file"
                        className="hidden"
                        accept="image/*"
                        onChange={(e) => handleFileChange(e, "photo")}
                      />
                    </label>
                  )}
                  {errors.photo && (
                    <motion.p
                      initial={{ opacity: 0, y: -10 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="mt-1 text-sm text-red-600"
                    >
                      {errors.photo.message as string}
                    </motion.p>
                  )}
                </div>
              </div>

              {/* Nominee Information Section */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-6 border-t">
                <div className="space-y-4 md:col-span-2">
                  <h2 className="text-lg font-semibold text-gray-800 border-b pb-2">
                    নমিনির তথ্য
                  </h2>
                </div>

                <Input
                  label="নমিনির নাম"
                  type="text"
                  icon={User}
                  placeholder="নমিনির পূর্ণ নাম দিন"
                  {...register("nomineeName")}
                  error={errors.nomineeName?.message}
                />

                <Input
                  label="নমিনির এনআইডি"
                  type="text"
                  icon={CreditCard}
                  placeholder="নমিনির জাতীয় পরিচয়পত্র নম্বর দিন (১০ সংখ্যা)"
                  {...register("nomineeNid")}
                  error={errors.nomineeNid?.message}
                />

                {/* Nominee Photo Upload */}
                <div className="w-full md:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    নমিনির ছবি <span className="text-red-500">*</span>
                  </label>
                  {nomineePhoto ? (
                    <div className="relative">
                      <div
                        className={`flex items-center space-x-3 p-3 border-2 rounded-lg transition-colors ${errors.nomineePhoto
                          ? "border-red-500 bg-red-50"
                          : "border-primary-300 bg-primary-50"
                          }`}
                      >
                        <Image className="h-8 w-8 text-primary-600" />
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium text-gray-700 truncate">
                            {nomineePhoto.name}
                          </p>
                          <p className="text-xs text-gray-500">
                            {(nomineePhoto.size / 1024).toFixed(2)} KB
                          </p>
                        </div>
                        <button
                          type="button"
                          onClick={() => removeFile("nomineePhoto")}
                          className="p-1 hover:bg-red-100 rounded-full transition-colors"
                        >
                          <X className="h-5 w-5 text-red-600" />
                        </button>
                      </div>
                    </div>
                  ) : (
                    <label
                      className={`flex flex-col items-center justify-center w-full h-32 border-2 border-dashed rounded-lg cursor-pointer transition-colors ${errors.nomineePhoto
                        ? "border-red-500 bg-red-50 hover:bg-red-100"
                        : "border-gray-300 bg-gray-50 hover:bg-gray-100"
                        }`}
                    >
                      <div className="flex flex-col items-center justify-center pt-5 pb-6">
                        <Upload
                          className={`w-8 h-8 mb-2 ${errors.nomineePhoto ? "text-red-400" : "text-gray-400"
                            }`}
                        />
                        <p className="mb-2 text-sm text-gray-500">
                          <span className="font-semibold">ক্লিক করুন</span> অথবা ফাইল টেনে আনুন
                        </p>
                        <p className="text-xs text-gray-500">PNG, JPG, JPEG (সর্বোচ্চ ৫ এমবি)</p>
                      </div>
                      <input
                        type="file"
                        className="hidden"
                        accept="image/*"
                        onChange={(e) => handleFileChange(e, "nomineePhoto")}
                      />
                    </label>
                  )}
                  {errors.nomineePhoto && (
                    <motion.p
                      initial={{ opacity: 0, y: -10 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="mt-1 text-sm text-red-600"
                    >
                      {errors.nomineePhoto.message as string}
                    </motion.p>
                  )}
                </div>
              </div>

              {/* Reference Information Section */}
              <div className="grid grid-cols-1 gap-6 pt-6 border-t">
                <div className="space-y-4">
                  <h2 className="text-lg font-semibold text-gray-800 border-b pb-2">
                    রেফারেন্সের তথ্য
                  </h2>
                </div>

                <Input
                  label="রেফারেন্সের নাম"
                  type="text"
                  icon={User}
                  placeholder="রেফারেন্সের পূর্ণ নাম দিন"
                  {...register("referenceName")}
                  error={errors.referenceName?.message}
                  className="md:col-span-2"
                />
              </div>

              <div className="flex items-start pt-6 border-t">
                <input
                  type="checkbox"
                  className="mt-1 w-4 h-4 text-primary-600 border-gray-300 rounded focus:ring-primary-500"
                  {...register("termsAccepted")}
                />
                <label className="ml-2 text-sm text-gray-600">
                  আমি{" "}
                  <Link
                    href="/terms"
                    rel="noopener noreferrer"
                    className="text-primary-600 hover:text-primary-700 font-medium underline"
                  >
                    শর্তাবলী
                  </Link>{" "}
                  এবং{" "}
                  <Link
                    href="/privacy"
                    rel="noopener noreferrer"
                    className="text-primary-600 hover:text-primary-700 font-medium underline"
                  >
                    গোপনীয়তা নীতি
                  </Link>{" "}
                  এর সাথে সম্মত
                </label>
              </div>
              {errors.termsAccepted && (
                <motion.p
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="text-sm text-red-600"
                >
                  {errors.termsAccepted.message}
                </motion.p>
              )}

              <Button
                type="submit"
                variant="primary"
                size="lg"
                className="w-full"
                isLoading={authLoading}
                icon={ArrowRight}
                disabled={authLoading}
              >
                অ্যাকাউন্ট তৈরি করুন
              </Button>
            </form>

            <div className="mt-6">
              <div className="relative">
                <div className="absolute inset-0 flex items-center">
                  <div className="w-full border-t border-gray-300"></div>
                </div>
                <div className="relative flex justify-center text-sm">
                  <span className="px-2 bg-white text-gray-500">
                    ইতিমধ্যে অ্যাকাউন্ট আছে?
                  </span>
                </div>
              </div>

              <Link href="/login">
                <Button
                  variant="outline"
                  size="lg"
                  className="w-full mt-4"
                  type="button"
                >
                  সাইন ইন করুন
                </Button>
              </Link>
            </div>
          </motion.div>
        </SlideIn>
      </div>
    </div>
  );
}
